services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8005:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

  mongo1:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


  mongo-express1:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8006:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

  api:
    build: .
    container_name: project_api
    ports:
      - "8001:8000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=project_management
    volumes:
      - ./app:/app


volumes:
  mongo_data:

networks:
  app-network:
